################################# Argument description ##################################################

# modules = Names of modules separated with comma, "all" for running analysis on all modules
# analysis.type= one of the following options (or more than one separated by comma)
#        "lm" -> Linear regression adjusted for all covariates
#        "cor" -> Pearson correlation for numeric variables and Spearman correlation for categorical variables
#        "test" -> Pearson correlation for numeric variables
#                 t-test for binary variables
#                 anova test for categorical and numeric variables

# calc_ME= "yes" or "no", Calculate Module Eigengene from expression matrix
# corr.plot= "yes" or "no" , correlation plot between MEs and phenotype of interest
# scatter.plot= "yes", "no" , Scatter plot for MEs and categorical variables
# save_csv = "yes" , or "no", Save the results in csv format

#########################################################################################################
argument <-   commandArgs(T)

net.file = trimws(argument[1])
expr.file = trimws(argument[2])
pheno.file = trimws(argument[3])
covars_fact = trimws(argument[4])
covars_num = trimws(argument[5])
modules = trimws(argument[6])
analysis.type = trimws(argument[7])
calc_ME = trimws(argument[8])
SoftPow = as.numeric(trimws(argument[9]))
corr.plot= trimws(argument[10])
scatter.plot = trimws(argument[11])
save_csv= trimws(argument[12])
out_pref = trimws(argument[13])

cat("Input arguments:\n")
cat("     Network object (generated by WGCNA) file = ",net.file,"\n")
cat("     Expression/Methylation matrix file = ",expr.file,"\n")
cat("     Phenotype data file = ",pheno.file,"\n")
cat("     Output files prefix = ",out_pref,"\n")
cat("\n")
cat("     Factor variables = ",covars_fact,"\n")
cat("     Numeric variables = ",covars_num,"\n")
cat("     Modules = ",modules,"\n")
cat("     Analysis type = ",analysis.type,"\n")
cat("     Do you want to calculate ME from expr/methyl matrix? ",calc_ME,"\n")
cat("     Softthrshold power (For calculating ME) = ",SoftPow,"\n")
cat("     Do you want to generate correlation plot? ",corr.plot,"\n")
cat("     Do you want to generate scatter plot? ",scatter.plot,"\n")
cat("     Do you want to save results in a csv file? ",save_csv,"\n")
cat("\n")
cat("Loading libraries...\n")

suppressMessages(library(WGCNA))
suppressMessages(library(stringr))
suppressMessages(library(gridExtra))
suppressMessages(library(stringr))
suppressMessages(library(funr))
suppressMessages(library(ggpubr))
cat("\n")
source(paste0(dirname(sys.script()),"/WGCNA.ModuleTrait.Function.R"))

scatter.smooth.with.lm <- function(x, y, xlabel="",ylabel="", title=""){
  library(ggplot2)
  
  data=cbind.data.frame(x,y)
  
  model <- lm(y ~ x, data = data)
  pval  <- summary(model)$coefficients[2, 4]
  pval_txt <- formatC(pval, format = "e", digits = 2)
  
    ggplot(data = data, aes(x, y)) + geom_point() +
    geom_smooth(method = "lm", formula = y ~ x , se = T) + 
      ggtitle(paste0(title , ", P-value = ",pval_txt))+xlab(xlabel)+ylab(ylabel)
}

###############################################################

cat("Reading Inputs...\n")

calc_ME = ifelse(tolower(calc_ME)=="yes",T,F)
corr.plot= ifelse(tolower(corr.plot)=="yes",T,F)
scatter.plot = ifelse(tolower(scatter.plot)=="yes",T,F)
save_csv= ifelse(tolower(save_csv) =="yes",T,F)

covars_fact=trimws(str_split_1(covars_fact,pattern = ','))
covars_num=trimws(str_split_1(covars_num,pattern = ','))
modules=trimws(str_split_1(modules,pattern = ','))
analysis.type = trimws(str_split_1(tolower(analysis.type) , pattern = "," ))

pheno = read.csv(pheno.file,row.names = 1,stringsAsFactors = F)
if(str_ends(expr.file , pattern = ".rds")){
  expr = readRDS(expr.file)
}else{
  expr = read.table(file = expr.file, stringsAsFactors = F,header = T, row.names = 1,check.names=F)
}

net = readRDS(net.file)

if(!identical(names(net$colors),rownames(expr))){
  warning("CpG/gene IDs in network and beta files are not match. It will be matched using shared CpGs...")
  index = intersect(names(net$colors),rownames(expr))
  expr = expr[index , ]
  net$colors = net$colors[index]
}
if(!identical(colnames(expr) , rownames(pheno))){
  warning("Sample IDs in phenotype and beta files are not match. It will be matched using shared samples...")
  index = intersect(colnames(expr) , rownames(pheno))
  expr = expr[,index]
  pheno = pheno[index ,]
}

if(tolower(modules=="all")){
  modules = unique(net$colors)
}

if(calc_ME){
  cat("Calculating Module Eigengenes...\n")
  Mes = moduleEigengenes(expr = t(expr) , colors = net$colors,softPower = SoftPow)$eigengenes
  net$MEs = Mes
}

colnames(net$MEs) <- str_remove(colnames(net$MEs),pattern = "ME")

for (k in 1:length(analysis.type)) {
  
  cat("Analysis based on ",analysis.type[k], "method...\n")
  
  result <- ModuleTrait(MEs = net$MEs[,modules , drop = F] , Pheno = pheno , method = analysis.type[k],Plot = T,plot.title = "Module Trait",
                        return_melt = F, Factor_Covars = covars_fact , Numeric_Covars = covars_num)
  
  if(save_csv){
    cat("Saving results in CSV file...\n")
    modules.size <- as.data.frame(table(net$colors))
    index <- match(rownames(result$Result),modules.size$Var1)
    result$Result$ModuleSize <- modules.size$Freq[index]
    write.csv(result$Result , file=paste0(out_pref,".ModuleTrait.",analysis.type[k],".csv"))
  }
  if(corr.plot){
    cat("Generating corrilation plot...\n")
    pdf(file = paste0(out_pref,".ModuleTrait.",analysis.type[k],"CorPlot.pdf"), width = 10, height = 10)
    print(result$Plot)
    graphics.off()
  }
  
  if(scatter.plot){
    cat("Generating scatter plots...\n")
    for (v in covars_fact) {
      p=list()
      for (i in 1:length(modules)) {
        p[[modules[i]]] = scatter.smooth.with.lm(x = as.numeric(as.factor(pheno[,v])),y = net$MEs[,modules[i]],xlabel = v,ylabel = "ME",title = modules[i])
      }
      
      pdf(file = paste0(out_pref,"ModuleTrait.",analysis.type[k],".",v,".ScatPlot.pdf"), width = 10, height = 10)
      grid.arrange(grobs=p)
      graphics.off()
    }

  }
  
}


