################################# Argument description ##################################################

# modules = Names of modules separated with comma, "all" for running analysis on all modules
# analysis.type= one of the following options (or more than one separated by comma)
#        "lm" -> Linear regression adjusted for all covariates
#        "cor" -> Pearson correlation for numeric variables and Spearman correlation for categorical variables
#        "test" -> Pearson correlation for numeric variables
#                 t-test for binary variables
#                 anova test for categorical and numeric variables

# calc_ME= "yes" or "no", Calculate Module Eigengene from expression matrix
# corr.plot= "yes" or "no" , correlation plot between MEs and phenotype of interest
# scatter.plot= "yes", "no" , Scatter plot for MEs and Trait variable
# save_csv = "yes" , or "no", Save the results in csv format

#########################################################################################################
argument <-   commandArgs(T)

net.file = trimws(argument[1])
expr.file = trimws(argument[2])
pheno.file = trimws(argument[3])
trait = trimws(argument[4])
covars_fact = trimws(argument[5])
covars_num = trimws(argument[6])
modules = trimws(argument[7])
analysis.type = trimws(argument[8])
calc_ME = trimws(argument[9])
SoftPow = as.numeric(trimws(argument[10]))
corr.plot= trimws(argument[11])
scatter.plot = trimws(argument[12])
save_csv= trimws(argument[13])
out_pref = trimws(argument[14])

cat("Input arguments:\n")
cat("     Network object (generated by WGCNA) file = ",net.file,"\n")
cat("     Expression/Methylation matrix file = ",expr.file,"\n")
cat("     Phenotype data file = ",pheno.file,"\n")
cat("     Output files prefix = ",out_pref,"\n")
cat("\n")
cat("     Trait variable = ",trait,"\n")
cat("     Factor variables = ",covars_fact,"\n")
cat("     Numeric variables = ",covars_num,"\n")
cat("     Modules = ",modules,"\n")
cat("     Analysis type = ",analysis.type,"\n")
cat("     Do you want to calculate ME from expr/methyl matrix? ",calc_ME,"\n")
cat("     Softthrshold power (For calculating ME) = ",SoftPow,"\n")
cat("     Do you want to generate correlation plot? ",corr.plot,"\n")
cat("     Do you want to generate scatter plot? ",scatter.plot,"\n")
cat("     Do you want to save results in a csv file? ",save_csv,"\n")
cat("\n")
cat("Loading libraries...\n")

suppressMessages(library(WGCNA))
suppressMessages(library(stringr))
suppressMessages(library(gridExtra))
suppressMessages(library(funr))

source(paste0(dirname(sys.script()),"/WGCNA.ModuleTrait.Function.R"))

###############################################################

cat("Reading Inputs...\n")

calc_ME = ifelse(tolower(calc_ME)=="yes",T,F)
corr.plot= ifelse(tolower(corr.plot)=="yes",T,F)
scatter.plot = ifelse(tolower(scatter.plot)=="yes",T,F)
save_csv= ifelse(tolower(save_csv) =="yes",T,F)

covars_fact=str_split(covars_fact,pattern = ',',simplify = T)[1,]
covars_num=str_split(covars_num,pattern = ',',simplify = T)[1,]
modules=str_split(modules,pattern = ',',simplify = T)[1,]
analysis.type = str_split(tolower(analysis.type) , pattern = "," , simplify = T)[1,]

pheno = read.csv(pheno.file,row.names = 1,stringsAsFactors = F)
expr = readRDS(expr.file)
net = readRDS(net.file)

if(!identical(names(net$colors),rownames(expr))){
  warning("CpG/gene IDs in network and beta files are not match. It will be matched using shared CpGs...")
  index = intersect(names(net$colors),rownames(expr))
  expr = expr[index , ]
  net$colors = net$colors[index]
}
if(!identical(colnames(expr) , rownames(pheno))){
  warning("Sample IDs in phenotype and beta files are not match. It will be matched using shared samples...")
  index = intersect(colnames(expr) , rownames(pheno))
  expr = expr[,index]
  pheno = pheno[index ,]
}

pheno <- pheno[,c(trait,covars_fact,covars_num)]
pheno[,trait] <- as.numeric(as.factor(pheno[,trait]))

if(covars_fact[1] != ""){
  for (i in 1:length(covars_fact)) {
    pheno[,covars_fact[i]] <- as.numeric(as.factor(pheno[,covars_fact[i]]))
  }
}
  
if(covars_num[1] != ""){
  for (i in 1:length(covars_num)) {
    pheno[,covars_num[i]] <- as.numeric(pheno[,covars_num[i]])
  }
}

if(tolower(modules=="all")){
  modules = unique(net$colors)
}

if(calc_ME){
  cat("Calculating Module Eigengenes...\n")
  Mes = moduleEigengenes(expr = t(expr) , colors = net$colors,softPower = SoftPow)$eigengenes
  net$MEs = Mes
}

colnames(net$MEs) <- str_remove(colnames(net$MEs),pattern = "ME")

for (k in 1:length(analysis.type)) {
  
  cat("Analysis based on ",analysis.type[k], "method...\n")
  
  result <- data.frame.relationship(df1 = net$MEs[,modules],df2 = pheno,method = analysis.type[k], 
                                    plot.title = paste("ME-Trait using",analysis.type[k],"correlation"),
                                    return_melt = F,Plot = corr.plot,categorical_columns = c(trait,covars_fact))
  
  cat("Saving results...\n")
  if(save_csv){
    modules.size <- as.data.frame(table(net$colors))
    index <- match(rownames(result$Result),modules.size$Var1)
    result$Result$ModuleSize <- modules.size$Freq[index]
    trait.pval <- result$Result[,paste0(trait,".Pvalue")]
    result$Result <- result$Result[order(trait.pval,decreasing = F),]
    write.csv(result$Result , file=paste0(out_pref,".ModuleTrait.",analysis.type[k],".csv"))
  }
  if(corr.plot){
    pdf(file = paste0(out_pref,".ModuleTrait.",analysis.type[k],"CorPlot.pdf"), width = 10, height = 10)
    print(result$Plot)
    graphics.off()
  }
  
  if(scatter.plot){
    p=list()
    for (i in 1:length(modules)) {
      p[[modules[i]]] = scatter.smooth.with.lm(pheno[,trait],net$MEs[,modules[i]],xlabel = trait,ylabel = "ME",title = modules[i])
    }
    
    pdf(filename = paste0(out_pref,"ModuleTrait.",analysis.type[k],".ScatPlot.pdf"), width = 10, height = 10)
    grid.arrange(grobs=p)
    graphics.off()
  }
  
}

